---
- name: Beispiel
  hosts: PXEAnsibleDC-Test
  become: true
  tasks:
    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Verify Apache2 installation
      shell: dpkg -l | grep apache2
      register: apache2_installed
      ignore_errors: yes

    - name: Debug Apache2 installation result
      debug:
        var: apache2_installed

    - name: Check Apache service status
      shell: systemctl status apache2
      register: apache2_status
      ignore_errors: yes

    - name: Debug Apache service status
      debug:
        var: apache2_status

    - name: Check alternative Apache service names
      shell: systemctl list-units --type=service | grep -i 'apache\|httpd\|www'
      register: alternative_apache_services
      ignore_errors: yes

    - name: Debug alternative Apache services
      debug:
        var: alternative_apache_services

    - name: Start Apache service
      service:
        name: apache2  # Behalten Sie 'apache2' bei oder passen Sie ihn an, basierend auf den Debug-Ergebnissen
        state: started
        

    - name: Create content
      copy:
        content: "Hallo Shrek"
        dest: /var/www/html/index.html
