---
- name: Clone and Start VMs from Template on Proxmox
  hosts: 10.80.15.32
  vars:
    proxmox_user: 'root@pam'
    proxmox_password: 'Zli12345'
    proxmox_node: 'diego-proxmox-srv'
    template_id: 1000  # ID der Vorlage (Template)
    num_vms: 3  # Anzahl der zu erstellenden VMs
  tasks:
    - name: Activate Python virtual environment and run script
      ansible.builtin.shell: |
        . /root/proxmoxer-venv/bin/activate && python3 - <<EOF
        from proxmoxer import ProxmoxAPI
        import requests

        # Deaktivieren der SSL-Verifizierung (nicht empfohlen in Produktionsumgebungen)
        proxmox = ProxmoxAPI('{{ inventory_hostname }}', user='{{ proxmox_user }}', password='{{ proxmox_password }}', verify_ssl=False)

        for i in range({{ num_vms }}):
            new_vm_id = {{ template_id }} + i + 1
            new_vm_name = 'VM' + str(new_vm_id)

            # Cloning VM from Template (template_id) to new_vm_name
            proxmox.nodes('{{ proxmox_node }}').qemu.post(
                create='clone',
                vmid=new_vm_id,
                name=new_vm_name,
                full='false',
                target='local'
            )

            # Starting the cloned VM
            proxmox.nodes('{{ proxmox_node }}').qemu(new_vm_id).status.post(ostart='true')
        EOF
      register: proxmox_output
      changed_when: "proxmox_output.rc != 127"
