---
- name: Create and start VMs using Proxmox VM module
  hosts: PXEAnsibleDC-Proxmox
  gather_facts: no

  vars:
    ansible_python_interpreter: "/root/proxmoxer-venv/bin/python3"
    template_id: 1000  # Die ID des Vorlagen-VMs
    vm_count: 3  # Anzahl der zu erstellenden VMs

  tasks:
    - name: Clone the template to create multiple VMs
      community.general.proxmox_vm:
        api_user: root@pam
        api_password: Zli12345
        api_host: 10.80.15.32
        node: diego-proxmox-srv
        vmid: "{{ 1100 + item }}"  # Neue VM-IDs für die geklonten VMs
        name: "VM-auto-{{ '%04d'|format(item) }}"
        clone: "{{ template_id }}"
        state: present
      loop: "{{ range(1, vm_count + 1) }}"  # Erstellt VMs mit fortlaufenden Nummern

    - name: Start the created VMs
      community.general.proxmox_vm:
        api_user: root@pam
        api_password: Zli12345
        api_host: 10.80.15.32
        node: diego-proxmox-srv
        name: "VM-auto-{{ '%04d'|format(item) }}"
        state: started
      loop: "{{ range(1, vm_count + 1) }}"  # Startet die erstellten VMs
