---
- name: Clone template and create VMs using Proxmox KVM module
  hosts: PXEAnsibleDC-Proxmox
  gather_facts: no

  vars:
    ansible_python_interpreter: "/root/proxmoxer-venv/bin/python3"
    api_user: root@pam
    api_password: Zli12345
    api_host: 10.80.15.32
    node: diego-proxmox-srv
    template_id: 1000  # ID der Vorlage, die geklont werden soll

  tasks:
    - name: Clone the template to create multiple VMs
      community.general.proxmox_template:
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        node: "{{ node }}"
        src: "{{ template_id }}"
        vmid: "{{ 2000 + item }}"  # ID der neuen VM, z.B. 2001, 2002, 2003
        name: "VM-auto-{{ '%04d'|format(item) }}"
        template: false  # Die geklonte VM soll kein Template sein
        state: present
      loop: "{{ range(1, 4) }}"

    - name: Start the cloned VMs
      community.general.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        node: "{{ node }}"
        name: "VM-auto-{{ '%04d'|format(item) }}"
        vmid: "{{ 2000 + item }}"  # ID der neuen VM, z.B. 2001, 2002, 2003
        state: started
      loop: "{{ range(1, 4) }}"
