---
- name: Clone and Start VMs from Template by ID
  hosts: PXEAnsibleDC-Proxmox
  vars:
    proxmox_api_host: "https://10.80.15.32:8006/api2/json"
    proxmox_api_user: "root@pam"
    proxmox_api_password: "zli12345"
    vm_node: "diego-proxmox-srv"
    vm_count: 3  # Anzahl der zu erstellenden und zu startenden VMs
    vm_template_id: 1000  # ID der Vorlage, die für die VM-Erstellung verwendet wird
  tasks:
    - name: Clone and Start VMs
      python:
        client: "{{ proxmox_api_host }}"
        user: "{{ proxmox_api_user }}"
        password: "{{ proxmox_api_password }}"
        node: "{{ vm_node }}"
        vmid: "{{ 2000 + vm_index }}"
        template: "{{ vm_template_id }}"
        clone: yes
        state: started
      loop: "{{ range(0, vm_count) | list }}"
      loop_control:
        loop_var: vm_index
