---
- name: VMs erstellen
  hosts: PXEAnsibleDC-Proxmox
  gather_facts: false

  vars:
    vm_count: 2
    base_name: "VM-auto"
    starting_id: 2400
    ansible_python_interpreter: "/root/proxmoxer-venv/bin/python3"
    api_user: "root@pam"
    api_password: "Zli12345"
    api_host: "10.80.15.32"
    bridge_interface: "vmbr1"
    discord_webhook_id: "1253674735649161247"
    discord_webhook_token: "vXToJvvUcKHB6u40F5GfRUcN0Fe4ORa5tQDu5Sifp-J1EHU0RkTMQ4EfjNkfSJRtJpr1"

  tasks:
    - name: Neue VM erstellen
      community.general.proxmox_kvm:
        node: diego-proxmox-srv
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        name: "{{ base_name }}-{{ starting_id + item }}"
        vmid: "{{ starting_id + item }}"
        ipconfig: '{"ipconfig0": "ip=dhcp"}'
        cores: 3
        memory: 2048
        scsihw: virtio-scsi-pci
        scsi: scsi='{"WDC-1TB_sdc-HDD":"32", "format":"qcow2"}'
        bios: ovmf
        net:
          net0: 'virtio,bridge={{ bridge_interface }}'
        state: present
      loop: "{{ range(1, vm_count + 1) | list }}"
      loop_control:
        loop_var: item
      register: vm_creation_results

    - name: Festplatte für VM erstellen (force rewrite in case it exists already)
      community.general.proxmox_disk:
        api_host: "{{ api_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        vmid: "{{ starting_id + item }}"
        disk: "scsi3"
        format: "qcow2"
        storage: "local"
        size: 16
        create: "forced"
        state: "present"
      loop: "{{ range(1, vm_count + 1) | list }}"
      loop_control:
        loop_var: item

    - name: Nachricht in Discord senden
      community.general.discord:
        webhook_id: "{{ discord_webhook_id }}"
        webhook_token: "{{ discord_webhook_token }}"
        content: "VM {{ base_name }}-{{ starting_id + item }} wurde erfolgreich erstellt."
      loop: "{{ range(1, vm_count + 1) | list }}"
      loop_control:
        loop_var: item
