---
- name: Create and start VMs using Cloud-Init template
  hosts: PXEAnsibleDC-Proxmox  # Hosts auf localhost setzen, da Ansible lokal aufgerufen wird
  gather_facts: no  # Keine Fakten über den Host sammeln

  tasks:
    - name: Create and start multiple VMs
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: Zli12345
        api_host: 10.80.15.32
        node: diego-proxmox-srv
        name: "VM-auto-{{ '%04d'|format(item) }}"  # Name wird mit fortlaufender Nummer erstellt
        clone: true  # Kopieren eines bestehenden Templates
        template: 1000  # ID des vorhandenen Templates, das kopiert werden soll
        state: started
      loop: "{{ range(1, 4) }}"  # Erstellt drei VMs mit den Nummern 1, 2 und 3
