---
- name: Create multiple VMs using Cloud-Init and DHCP configuration
  hosts: PXEAnsibleDC-Proxmox
  gather_facts: false

  vars:
    vm_count: 2
    base_name: "VM-auto"
    starting_id: 2107
    ansible_python_interpreter: "/root/proxmoxer-venv/bin/python3"
    api_user: "root@pam"
    api_password: "Zli12345"
    api_host: "10.80.15.32"
    bridge_interface: "vmbr1"
    discord_webhook_id: "1253674735649161247"
    discord_webhook_token: "vXToJvvUcKHB6u40F5GfRUcN0Fe4ORa5tQDu5Sifp-J1EHU0RkTMQ4EfjNkfSJRtJpr1"

  tasks:
    - name: Create new VM using Cloud-Init and DHCP configuration
      community.general.proxmox_kvm:
        node: diego-proxmox-srv
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        name: "{{ base_name }}-{{ starting_id + (item - 1) }}"
        vmid: "{{ starting_id + (item - 1) }}"
        ide:
          ide2: 'local:cloudinit,format=qcow2'
        ipconfig: '{"ipconfig0": "ip=dhcp"}'
        cores: 3
        memory: 2048
        scsi: scsi='{"WDC-1TB_sda-HDD:16,format=qcow2"}'
        bios: ovmf
        scsihw: virtio-scsi-pci
        net:
          net0: 'virtio,bridge={{ bridge_interface }}'
        state: present
      loop: "{{ range(1, vm_count + 1) | list }}"
      loop_control:
        loop_var: item
      register: vm_creation_results

    - name: Gather VM information
      community.general.proxmox_vm_info:
        node: diego-proxmox-srv
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
      register: vm_info

    - name: Extract IP and MAC addresses of created VMs
      set_fact:
        vm_info_list: "{{ vm_info.virtual_machines | map(attribute='name') | list }}"

    - name: Send VM information to Discord channel
      community.general.discord:
        webhook_id: "{{ discord_webhook_id }}"
        webhook_token: "{{ discord_webhook_token }}"
        content: |
          VM creation completed successfully.

          {% for vm_name in vm_info_list %}
          Name: {{ vm_name }}
          IP Address: {{ hostvars[inventory_hostname]['ansible_' + 'ipv4']['address'] }}
          MAC Address: {{ hostvars[inventory_hostname]['ansible_' + 'enp0s3']['macaddress'] }}
          {% endfor %}
