---
- name: Create and start VMs using Proxmox KVM module
  hosts: PXEAnsibleDC-Proxmox
  gather_facts: no

  vars:
    ansible_python_interpreter: "/root/proxmoxer-venv/bin/python3"

  tasks:
    - name: Clone the template to create multiple VMs
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: Zli12345
        api_host: 10.80.15.32
        node: diego-proxmox-srv
        name: "VM-auto-{{ '%04d'|format(item) }}"
        clone: true  # Cloning the existing template
        template: 1000  # ID of the VM template
        state: present
      loop: "{{ range(1, 4) }}"  # Creates three VMs with numbers 1, 2, and 3

    - name: Start the created VMs
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: Zli12345
        api_host: 10.80.15.32
        node: diego-proxmox-srv
        name: "VM-auto-{{ '%04d'|format(item) }}"
        state: started
      loop: "{{ range(1, 4) }}"  # Starts the three VMs created above
