---
- name: Create VMs in Proxmox from Template by ID
  hosts: PXEAnsibleDC-Proxmox
  gather_facts: false
  vars:
    proxmox_api_host: "https://10.80.15.32:8006/api2/json"
    proxmox_api_user: "root@pam"
    proxmox_api_password: "Zli12345"
    vm_node: "diego-proxmox-srv"
    vm_name_prefix: "vm-auto-"
    vm_template_id: 1000  # Hier die ID der VM-Vorlage eintragen
    vm_count: 3

  tasks:
    - name: Clone VMs from Template by ID
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        node: "{{ vm_node }}"
        vmid: "{{ 2000 + vm_index }}"
        name: "{{ vm_name_prefix }}{{ '%04d' | format(vm_index + 1) }}"
        clone: "{{ vm_template_id }}"  # Dies ist der richtige Parameter zum Klonen
        full: false
        state: present
      loop: "{{ range(0, vm_count) | list }}"
      loop_control:
        loop_var: vm_index

    - name: Start cloned VMs
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        node: "{{ vm_node }}"
        vmid: "{{ 2000 + vm_index }}"
        state: started
      loop: "{{ range(0, vm_count) | list }}"
      loop_control:
        loop_var: vm_index
