---
- name: Create VMs in Proxmox from Template
  hosts: PXEAnsibleDC-Proxmox
  gather_facts: false
  vars:
    # Proxmox API credentials with username and password
    proxmox_api_host: "https://10.80.15.32:8006/api2/json"
    proxmox_api_user: "root@pam"  # Ersetze durch deinen Proxmox API-Benutzernamen
    proxmox_api_password: "Zli12345"  # Ersetze durch dein Proxmox API-Passwort
    # VM-spezifische Variablen
    vm_node: "diego-proxmox-srv"  # Aktualisierter Hostname des Proxmox-Servers
    vm_id_start: 2000  # Start-ID für die neuen VMs
    vm_name_prefix: "vm-auto-"  # Präfix für die neuen VMs
    vm_template_vmid: 1000  # ID der vorhandenen Vorlage, die geklont werden soll
    vm_count: 3  # Anzahl der zu erstellenden VMs

  tasks:
    - name: Clone VMs from Template
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        node: "{{ vm_node }}"
        vmid: "{{ vm_id_start + vm_index }}"
        name: "{{ vm_name_prefix }}{{ '%04d' | format(vm_index + 1) }}"
        template: "{{ vm_template_vmid }}"  # Korrigierte Verwendung der Template-ID hier
        state: present
      loop: "{{ query('sequence', 'start=' ~ vm_id_start ~ ' count=' ~ vm_count) | map('int') }}"
      loop_control:
        loop_var: vm_index

    - name: Start cloned VMs
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        node: "{{ vm_node }}"
        vmid: "{{ vm_id_start + vm_index }}"
        state: started
      loop: "{{ query('sequence', 'start=' ~ vm_id_start ~ ' count=' ~ vm_count) | map('int') }}"
      loop_control:
        loop_var: vm_index
