---
- name: Create VMs in Proxmox from Template
  hosts: PXE-Ansible-Proxmox
  gather_facts: false
  vars:
    # Proxmox API credentials with API token
    proxmox_api_host: "https://10.80.15.32:8006/api2/json"
    proxmox_api_token: "e06dac6c-0c64-4166-9002-3342132e080a"  # Replace with your actual API token
    # VM specifics
    vm_node: "diego-proxmox-srv"
    vm_id_start: 2000  # Start-ID für die neuen VMs
    vm_name_prefix: "vm-auto-"  # Prefix für die neuen VMs
    vm_template_vmid: 1000  # ID des vorhandenen Templates, das geklont werden soll
    vm_count: 3  # Anzahl der zu erstellenden VMs

  tasks:
    - name: Clone VM from Template
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_api_host }}"
        api_token: "{{ proxmox_api_token }}"
        node: "{{ vm_node }}"
        vmid: "{{ item.id }}"
        name: "{{ item.name }}"
        clone: true
        clone_id: "{{ vm_template_vmid }}"
        state: present
      loop: "{{ query('sequence', 'start=' ~ vm_id_start ~ ' count=' ~ vm_count) }}"
      loop_control:
        loop_var: item
      vars:
        item:
          id: "{{ item }}"
          name: "{{ vm_name_prefix ~ '%04d' % (item - vm_id_start + 1) }}"

    - name: Start cloned VMs
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_api_host }}"
        api_token: "{{ proxmox_api_token }}"
        node: "{{ vm_node }}"
        vmid: "{{ item.id }}"
        state: started
      loop: "{{ query('sequence', 'start=' ~ vm_id_start ~ ' count=' ~ vm_count) }}"
      loop_control:
        loop_var: item
      vars:
        item:
          id: "{{ item }}"
          name: "{{ vm_name_prefix ~ '%04d' % (item - vm_id_start + 1) }}"
