---
- name: Clone and Start VMs from Template on Proxmox
  hosts: PXEAnsibleDC-Proxmox
  vars:
    proxmox_server: '10.80.15.32'  # Ihre Proxmox-Server-IP-Adresse
    proxmox_user: 'root@pam'  # Ihr Proxmox-Benutzername
    proxmox_password: 'Zli12345'  # Ihr Proxmox-Passwort
    proxmox_node: 'diego-proxmox-srv'  # Name des Proxmox-Knotens
    template_id: 1000  # ID der Vorlage (Template)
    num_vms: 3  # Anzahl der zu erstellenden VMs
  tasks:
    - name: Activate Python virtual environment
      ansible.builtin.command: /root/proxmoxer-venv/bin/activate
      environment:
        VIRTUAL_ENV: /root/proxmoxer-venv
      become: true
      become_user: root

    - name: Clone and Start VMs
      ansible.builtin.shell: |
        source /root/proxmoxer-venv/bin/activate &&
        python3 - <<EOF
        from proxmoxer import ProxmoxAPI

        proxmox = ProxmoxAPI('{{ proxmox_server }}', user='{{ proxmox_user }}', password='{{ proxmox_password }}', verify_ssl=False)

        for i in range({{ num_vms }}):
            new_vm_id = {{ template_id }} + i + 1
            new_vm_name = 'VM' + str(new_vm_id)

            # Cloning VM from Template (template_id) to new_vm_id
            proxmox.nodes('{{ proxmox_node }}').qemu.clone(
                newid=new_vm_id,
                name=new_vm_name,
                template={{ template_id }}
            )

            # Starting the cloned VM
            proxmox.nodes('{{ proxmox_node }}').qemu.status(new_vm_id).start()
        EOF
      register: proxmox_output
      changed_when: "proxmox_output.rc != 127"
