- name: Clone and Start VMs from Template on Proxmox
  hosts: localhost
  vars:
    proxmox_server: 'your.proxmox.server'  # Adresse Ihres Proxmox-Servers
    proxmox_user: 'your_user@pam'  # Ihr Benutzername für Proxmox
    proxmox_password: 'your_password'  # Ihr Passwort für Proxmox
    proxmox_node: 'my-proxmox-node'  # Name des Proxmox-Knotens
    template_id: 1000  # ID der Vorlage (Template)
    num_vms: 3  # Anzahl der zu erstellenden VMs
  tasks:
    - name: Clone and Start VMs
      shell: >
        /usr/bin/python3 - <<EOF
        from proxmoxer import ProxmoxAPI

        proxmox = ProxmoxAPI('{{ proxmox_server }}', user='{{ proxmox_user }}', password='{{ proxmox_password }}', verify_ssl=False)

        for i in range({{ num_vms }}):
            new_vm_id = {{ template_id }} + i + 1
            new_vm_name = 'VM' + str(new_vm_id)

            # Cloning VM from Template (template_id) to new_vm_id
            proxmox.nodes('{{ proxmox_node }}').qemu.clone(
                newid=new_vm_id,
                name=new_vm_name,
                template={{ template_id }}
            )

            # Starting the cloned VM
            proxmox.nodes('{{ proxmox_node }}').qemu.status(new_vm_id).start()
        EOF
      register: proxmox_output
      changed_when: "'task failed' not in proxmox_output.stderr"